name: exodus
description: Your money controller
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  # AppData packages
  flutter_svg: ^2.0.7
  logger: ^2.0.2+1
  url_launcher: ^6.1.14
  go_router: ^7.1.1
  easy_localization: ^3.0.3
  simple_progress_indicators: ^0.2.0 #Indicator package

  # Core packages
  dio: ^5.3.3
  path_provider: ^2.1.1
  get_it: ^7.6.4
  data_source:
    version: ^0.1.1
    git: https://github.com/dronn1k-org/data_source.git
  reactive_variables: ^0.1.0

  # Domain packages
  json_annotation: ^4.8.1

  # App packages
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  bip39_mnemonic: ^3.0.6
  convert: ^3.1.1
  simple_rc4: ^0.3.0
  fl_chart: ^0.63.0
  hdkey: ^0.0.1
  hex: ^0.2.0
  bip39: ^1.0.6
  web3dart: ^2.7.1
  http: ^1.1.0
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  msix: ^3.16.6
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

  firebase_core: ^2.24.2 
  cloud_firestore: ^4.14.0
  firebase_database: ^10.4.0
  firedart: ^0.9.7
  connectivity_plus: ^5.0.2

  #Tx app
  flutter_colorpicker: ^1.0.3
  flutter_iconpicker: ^3.2.4
  syncfusion_flutter_charts: ^24.2.3+1

  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  retrofit_generator: ^7.0.0
  build_runner: ^2.3.3
  isar_generator: ^3.1.0+1
  hive_generator: ^2.0.1
  flutter_launcher_icons: "^0.13.1"
  

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/1024.png"


msix_config:
  display_name: "Exodus Wallet : Portfolio App"  
  msix_version: 1.0.0
  logo_path: snap/gui//exodus.png
  publisher_display_name: TAN MY SON DESIGN
  identity_name: 23104TANMYSONDESIGN.SparrowWalletPortfolioApp
  publisher: CN=31F5764A-0855-45EA-85FC-A76470FBCC97
  store: true


flutter:


  uses-material-design: true

  assets:
    - assets/icons/
    - assets/crypto/
    - assets/layouts/
    - assets/images/
    - snap/gui/

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
